### ISSUE TITLE
Change listening IP from 'localhost' to something-else?

### ISSUE THREAD

**Issue by w0rd88** [shupp/VegaDNS-UI#1]
Hello.

It looks like VegaDNS-UI listens on 127.0.0.1:8080 by default.  Where can this be adjusted? 

Netstat output:
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN   

I would like to change the listening IP, however it would also be nice to know where port 8080 can be changed.  

Thanks,
-d

**Comment by shupp** [comment]
Sounds like you're talking about the development tool webpack.  In
production you'd run it under nginx.  See the docker directory for sample
configs.

**Comment by w0rd88** [comment]
Yes I think that's what I was missing.  Thank you for pointing that out!
