### ISSUE TITLE
Docker config doesn't work

### ISSUE THREAD

**Issue by w0rd88** [shupp/VegaDNS-UI#2]
Hello,

It looks like something is broken with the docker config.  I'm attempting to build using the following:

docker build --no-cache=false -t vegadns2-public https://raw.githubusercontent.com/shupp/VegaDNS-API/master/docker/Dockerfile

Step 17 : RUN chmod +x /var/www/vegadns2/docker/buildenv.sh
 ---> Running in fd340f6d919d
chmod: cannot access '/var/www/vegadns2/docker/buildenv.sh': No such file or directory
The command '/bin/sh -c chmod +x /var/www/vegadns2/docker/buildenv.sh' returned a non-zero code: 1

It looks like the Dockerfile is expecting the /var/www/vegadns2/ folder to contain both files from VegaDNS-API/ and VegaDNS-API/docker.  

Thanks,
-d

**Comment by shupp** [comment]
What version of docker are you using, and on what platform?

**Comment by w0rd88** [comment]
# docker -v
Docker version 1.12.1, build 23cf638

# dpkg --list | grep docker.io
ii  docker.io                          1.12.1-0ubuntu13~16.04.1           amd64        Linux container runtime

On ubuntu 16.04.  

Thanks for your help!
-d

**Comment by shupp** [comment]
Oh, you can't do it remotely.  Check out the repo, and look at
docker/build_image.sh.  It checks out dependencies.

**Comment by shupp** [comment]
I've updated the README.md file in the VegaDNS-API repo to cover this:

https://github.com/shupp/VegaDNS-API/commit/21965807cb64ec0ad4338b704255bf3839b915ce
