### ISSUE TITLE
Webpage console error, cant log in with test@test.com

### ISSUE THREAD

**Issue by akito2000** [shupp/VegaDNS-UI#6]
I have vegadns-api working and responding on port 5000, tested with curl and was able to request API keys.  Setup the UI on the same server, uncommented the line in public/index.html and the page displays fine but in the web browser console I get this error every time I click to login and the page does nothing.  Cant login with the default test@test.com account.  Am I doing something wrong in the installation?

![vegadns-ui](https://user-images.githubusercontent.com/45797568/49818000-8662b300-fd26-11e8-9c03-8cd20d421eef.JPG)

**Comment by shupp** [comment]
@akito2000 sorry you're having trouble.  Can you show the XHR call details to confirm it's talking to your API and on the right port?  Do the API logs indicate that it's getting the request, and if so what's wrong with it?

Alternatively, you can run this via docker-compose if you're just exploring.  From the VegaDNS-API repository, just do:

```
make pull up
LOGS_ARGS=" -f " make logs
```

Then login from the UI, and you should see any errors in your docker-compose logs.

**Comment by akito2000** [comment]
I tried it over the docker before and was getting the same issue which I initially believed was a problem with my docker setup so I moved to the venv setup to try and resolve it.  I have moved back to the docker setup and took the below from log.  The ui appears to be communicating but the login still doesnt work and the browser shows the same error in console.

![vegadns-ui2](https://user-images.githubusercontent.com/45797568/49822482-2540dc80-fd32-11e8-8bce-188aec71b264.JPG)

**Comment by shupp** [comment]
@akito2000 Ok, interesting. Unfortunately that bit of logs you provided doesn't cover the actual XHR request.  You can limit the log output to just the api by doing the following:

```
LOGS_ARGS=" -f api " make logs
```

When doing that, do you see the UI making a connection to the api?

FYI, I'm unable to duplicate this with the current image builds.

**Comment by akito2000** [comment]
I am not seeing the ui in there, no.  So then it must be a connection issue between the two docker containers? 

A little background, this is a VM running on Centos 7, no firewalld and only rules in iptables are the ones docker places there.

**Comment by akito2000** [comment]
I can see tinydns in there pretty consistently

**Comment by shupp** [comment]
@akito2000 It sounds like it.  docker-compose allows you to reference other containers by the name of the docker-compose entry.  And the UI container's index.html file is updated accordingly to point to that docker container.

LOGS_ARGS="" just allows you to pass "docker-compose logs" arguments through make.  -f is follow (ongoing log watching), and if no other args are supplied, you see all logs.  If you supply container names, like api or ui, you filter only those logs.  So you can play around to see what is actually happening.

Another option is to try the "apiui" container., which has the ui and the api in the same container.  (Simpler to manage for some deployments).

```
make down
make pull up-apiui
```

See if that works any better for you.

**Comment by akito2000** [comment]
So I thought maybe there was something on my centos image interfering so I reintalled centos from scratch, disabled selinux and firewalld then reinstalled the docker version.  I am still seeing the same issue on a fresh install.  Since we believed it was a connection issue between the docker containers I accessed the ui container via "docker exec -i -t vegadns-api_ui_1_49efaef6dc6f /bin/sh" and checked the index.html.  The index.html was still pointed at localhost:5000 so I modified that to try it to 172.18.0.5 (the api address), but had no luck.  I used "nc 172.18.0.5 5000" to test and that port is open to the ui container.

**Comment by shupp** [comment]
Ah, this might be related.  I think the docker-compose stuff is expecting the API to be on localhost by default.  In my situation, I'm using docker for mac, which does run docker on localhost.  Though the containers have NAT IPs internally, the UI's VegaDNSHost variable being localhost works from the client perspective.

172.18.0.5 appears to be one of docker's NAT ips, is that right?  What IP is your docker service running on?  If it's 127.0.0.1, then this is not the issue.  If it's something different, say 192.168.1.1, then you want to do something like this:

```
export API_URL="http://192.168.1.1:5000"
make down up-apiui
```

The API_URL variable is then populated in docker-compose, which is picked up by the ui or apiui containers, and then propagates down (via the entrypoint file) to the public/index.html file's VegaDNSHost variable.  Remember that this needs to be set to what your browser sees docker as, (the docker host), not the internal NAT ip of the docker container, which I think is what you reference above.

**Comment by akito2000** [comment]
Bingo, now the ui connects.  Thank you very much.

**Comment by shupp** [comment]
Good go hear!
